version: '3'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: siembrasana
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 8080:8080
volumes:
  postgres-data: